/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        // Original tokens
        clash:   ['"Clash Display"', 'sans-serif'],
        cabinet: ['"Cabinet Grotesk"', 'sans-serif'],
        serif:   ['"Instrument Serif"', 'serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
        // Aurelian Studio tokens
        'headline-xl':       ['Geist', '"Cabinet Grotesk"', 'sans-serif'],
        'headline-lg':       ['Geist', '"Cabinet Grotesk"', 'sans-serif'],
        'headline-lg-mobile':['Geist', '"Cabinet Grotesk"', 'sans-serif'],
        'headline-md':       ['Geist', '"Cabinet Grotesk"', 'sans-serif'],
        'body-lg':           ['Inter', '"Cabinet Grotesk"', 'sans-serif'],
        'body-md':           ['Inter', '"Cabinet Grotesk"', 'sans-serif'],
        'label-mono':        ['"JetBrains Mono"', 'monospace'],
        caption:             ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl':        ['64px',  { lineHeight: '72px',  letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg':        ['40px',  { lineHeight: '48px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px',  { lineHeight: '40px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':        ['24px',  { lineHeight: '32px',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg':            ['18px',  { lineHeight: '30px',  letterSpacing: '0.01em',  fontWeight: '400' }],
        'body-md':            ['16px',  { lineHeight: '26px',  letterSpacing: '0rem',    fontWeight: '400' }],
        'label-mono':         ['14px',  { lineHeight: '20px',  letterSpacing: '0.05em',  fontWeight: '500' }],
        caption:              ['12px',  { lineHeight: '16px',  letterSpacing: '0.02em',  fontWeight: '500' }],
      },
      colors: {
        // ── Original portfolio tokens ─────────────────
        obsidian: '#080810',
        void:     '#0c0c18',
        surface:  '#11111f',
        surface2: '#16162a',
        gold:     '#c9a84c',
        gold2:    '#e8c97a',
        amber:    '#f5a623',
        emerald2: '#00e5a0',
        cyan2:    '#00d4ff',

        // ── Aurelian Studio Tokens (static — same in light & dark) ─────
        'surface-dim':              '#131314',
        'surface-bright':           '#3a393a',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-low':    '#1c1b1c',
        'primary-fixed':            '#ffdea8',
        'primary-fixed-dim':        '#ffba20',
        'on-primary-fixed':         '#271900',
        'on-primary-fixed-variant': '#5e4200',
        'inverse-primary':          '#7c5800',
        'on-secondary':             '#3d2e00',
        'secondary-container':      '#785d00',
        'on-secondary-container':   '#fdd977',
        'secondary-fixed':          '#ffe08f',
        'secondary-fixed-dim':      '#e6c364',
        'on-secondary-fixed':       '#241a00',
        'on-secondary-fixed-variant':'#584400',
        tertiary:                   '#abebff',
        'on-tertiary':              '#003641',
        'tertiary-container':       '#00d7fe',
        'on-tertiary-container':    '#005a6b',
        'tertiary-fixed':           '#b0ecff',
        'tertiary-fixed-dim':       '#17d8ff',
        'on-tertiary-fixed':        '#001f27',
        'on-tertiary-fixed-variant':'#004e5d',
        error:                      '#ffb4ab',
        'on-error':                 '#690005',
        'error-container':          '#93000a',
        'on-error-container':       '#ffdad6',
        'inverse-surface':          '#e5e2e3',
        'inverse-on-surface':       '#313031',
        'surface-tint':             '#ffba20',
        'terminal-green':           '#00E5A0',

        // ── Aurelian Studio Tokens (adaptive via CSS vars) ─────────────
        'surface-container':        'var(--au-surface-container)',
        'surface-container-high':   'var(--au-surface-container-high)',
        'surface-container-highest':'var(--au-surface-container-highest)',
        'surface-elevated':         'var(--au-surface-elevated)',
        'surface-variant':          'var(--au-surface-variant)',
        'on-surface':               'var(--au-on-surface)',
        'on-surface-variant':       'var(--au-on-surface-variant)',
        'on-background':            'var(--au-on-surface)',
        background:                 'var(--au-background)',
        outline:                    'var(--au-outline)',
        'outline-variant':          'var(--au-outline-variant)',
        primary:                    'var(--au-primary)',
        'on-primary':               'var(--au-on-primary)',
        'primary-container':        'var(--au-primary-container)',
        'on-primary-container':     'var(--au-on-primary-container)',
        secondary:                  'var(--au-secondary)',
        'border-glass':             'var(--au-border-glass)',
        'accent-glow':              'var(--au-accent-glow)',
      },
      spacing: {
        unit:           '4px',
        'container-max':'1200px',
        gutter:         '24px',
        'margin-mobile':'20px',
        'section-gap':  '120px',
      },
      borderRadius: {
        sm:      '0.25rem',
        DEFAULT: '0.5rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'float':      'float 6s ease-in-out infinite',
        'marquee':    'marquee 25s linear infinite',
        'spin-slow':  'spin 3s linear infinite',
      },
      keyframes: {
        float: {
          '0%,100%': { transform: 'translateY(0px)' },
          '50%':     { transform: 'translateY(-16px)' },
        },
        marquee: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
}
